### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by mastrof** [mastrof/Bactos.jl#60]
- [ ] Improved constructors for all `AbstractMicrobe` subtypes and `ABM` to minimize verbosity and boilerplate code.
- [ ] Simple interface for pairwise microbe interactions (via `CellListMap.jl`).
- [ ] Improved interface with `OrdinaryDiffEq.jl` for seamless integration in standard use cases.
- [ ] Extended analysis toolkit.
- [ ] Extensive test suite covering all functionalities.
- [ ] Optimization and development of a benchmark suite.
- [ ] Submodule with `Plots.jl` (and `Makie.jl`?) recipes.
